{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "e382ec6a-60fe-491c-b056-ca2030f154b9",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Consensus sequence: ATGCAACT\n",
      "Profile Matrix:\n",
      "A : [5, 1, 0, 0, 5, 5, 0, 0]\n",
      "C : [0, 0, 1, 4, 2, 0, 6, 1]\n",
      "G : [1, 1, 6, 3, 0, 1, 0, 0]\n",
      "T : [1, 5, 0, 0, 0, 1, 1, 6]\n"
     ]
    }
   ],
   "source": [
    "# ============================================================\n",
    "# Consensus and Profile - Rosalind Problem\n",
    "# ============================================================\n",
    "\n",
    "\n",
    "# ----------------------------\n",
    "# 1. READ FASTA FILE\n",
    "# ----------------------------\n",
    "\n",
    "with open (\"example.fasta\", \"r\") as file:\n",
    "    fasta_dict = {}       # Dictionary to store {sequence_id: sequence_string}\n",
    "    sequence_id = []      # List to store all sequence IDs\n",
    "    sequence_string = []  # List to store full sequences\n",
    "    line_seqs = [ ]       # Temporary list to accumulate sequence lines\n",
    "\n",
    "\n",
    "    # Read each line from the FASTA file   \n",
    "    for line in file:\n",
    "        line = line.strip(\"\\n\")\n",
    "        if line.startswith(\">\"):\n",
    "            sequence_id.append(line[1:])   # Remove the \">\" before storing the ID.\n",
    "            if line_seqs != []:\n",
    "                full_seq = \"\".join(line_seqs)\n",
    "                sequence_string.append(full_seq)\n",
    "                line_seqs = []\n",
    "        else:\n",
    "            line_seqs.append(line)\n",
    "            \n",
    "# Save the last sequence.\n",
    "    if line_seqs != []:\n",
    "                full_seq = \"\".join(line_seqs)\n",
    "                sequence_string.append(full_seq)    \n",
    "              \n",
    "    for i in range(len(sequence_id)):\n",
    "        fasta_dict[sequence_id[i]] = sequence_string[i]\n",
    "\n",
    "\n",
    "# ----------------------------\n",
    "# 2. BUILD PROFILE MATRIX\n",
    "# ----------------------------\n",
    "\n",
    "# Initialize counts for each nucleotide at each position\n",
    "sequence_length = len(sequence_string[0])\n",
    "A = [0] * sequence_length\n",
    "C = [0] * sequence_length\n",
    "G = [0] * sequence_length\n",
    "T = [0] * sequence_length\n",
    "\n",
    "# Count nucleotides at each position across all sequences\n",
    "for seq in fasta_dict.values():\n",
    "    for i in range(len(seq)):\n",
    "        if seq[i] == \"A\":\n",
    "            A[i] += 1\n",
    "        elif seq[i] == \"C\":\n",
    "            C[i] += 1\n",
    "        elif seq[i] == \"G\":\n",
    "            G[i] += 1\n",
    "        elif seq[i] == \"T\":\n",
    "            T[i] += 1\n",
    "\n",
    "profile_counts = {\n",
    "    \"A\" : A,\n",
    "    \"C\" : C,\n",
    "    \"G\" : G,\n",
    "    \"T\" : T\n",
    "}\n",
    "\n",
    "\n",
    "# ----------------------------\n",
    "# 3. GENERATE CONSENSUS SEQUENCE\n",
    "# ----------------------------\n",
    "\n",
    "consensus_list = []\n",
    "\n",
    "# For each position, find the nucleotide with the highest count\n",
    "for i in range(sequence_length):\n",
    "    max_base = None\n",
    "    max_value = -1\n",
    "    for base, counts in profile_counts.items():\n",
    "        if counts[i] > max_value:\n",
    "            max_value = counts[i]\n",
    "            max_base = base\n",
    "    consensus_list.append(max_base)\n",
    "            \n",
    "# Convert consensus list to string    \n",
    "consensus_seq = \"\".join(consensus_list)\n",
    "\n",
    "\n",
    "# ----------------------------\n",
    "#  OUTPUT RESULTS\n",
    "# ----------------------------\n",
    "        \n",
    "print(f\"Consensus sequence: {consensus_seq}\")\n",
    "\n",
    "print(\"Profile Matrix:\")\n",
    "for key,value in profile_counts.items():\n",
    "    print(f\"{key} : {value}\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0b7fcc03-f3d9-4e23-a45f-404988ea3094",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f7b5ecde-4624-463e-88e3-bf3de3b8ad32",
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "        "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "226c1998-804b-474f-9795-8f8d13610abe",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
